### ISSUE TITLE
Como criar um request pra informar pagamento?

### ISSUE THREAD

**Issue by merceloki** [jetimob/juno-sdk-php-laravel#14]
Bom dia 

Como faço pra mandar um request de pagamento de cartao de credito para juno usando o sdk?

**Comment by alanwgt** [comment]
Olá, Marcelo!

Infelizmente, como não usamos a parte de pagamento por cartão, não implementamos essa funcionalidade.

Creio que não viremos a implementar isso em um futuro próximo :confused:

**Comment by merceloki** [comment]
> Olá, Marcelo!
> 
> Infelizmente, como não usamos a parte de pagamento por cartão, não implementamos essa funcionalidade.
> 
> Creio que não viremos a implementar isso em um futuro próximo 😕

entendi, posso implementar e fazer um pr?

**Comment by alanwgt** [comment]
Claro! Será muito bem vindo!

Muito obrigado pela disponibilidade. Surgindo dúvidas, não hesite em perguntar.

Abraço!
