### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by lpcs007** [jetimob/juno-sdk-php-laravel#41]
Sei que a Iugu comprou a Juno, mas ainda utilizo a Juno para recebimento de pagamentos.
Acontece que estou tentando usar o sdk, mas não está claro os comandos disponíveis.
Por exemplo, como faço para criar uma cobrança? como faço para gerar um qrcode pix? como faço para tokenizar o cartão de crédito?
Vendo nas issues fechadas, me parece que tinha essas informações no README, mas não tem mais.

Agradeço pela ajuda.

**Comment by alanwgt** [comment]
Opa, beleza?

Realmente, como a Juno vai deixar de existir, não demos a devida atenção para a documentação após o refactor para a v2.

Seguem os exemplos de uso:

> Criar uma cobrança

```php
// https://github.com/jetimob/juno-sdk-php-laravel/blob/05c7b3b988deba3aaa682a4e04fee30bfe88a4cd/src/Api/Charge/ChargeApi.php#L34
\Juno::charge->create($charge, $billing);
// os parâmetros *$charge* e *$billing* devem ser criados com os objetos encontrados em:
// https://github.com/jetimob/juno-sdk-php-laravel/blob/ae8ad9fe9b50b2033116e20b2ce0de31c7ce42ad/src/Entity/Charge.php
// https://github.com/jetimob/juno-sdk-php-laravel/blob/ae8ad9fe9b50b2033116e20b2ce0de31c7ce42ad/src/Entity/Billing.php
// E aqui um teste utilizado para criar a cobrança https://github.com/jetimob/juno-sdk-php-laravel/blob/master/tests/Feature/ChargeApiTest.php#L34
```

> Tokenizar cartão

```php
// https://github.com/jetimob/juno-sdk-php-laravel/blob/05c7b3b988deba3aaa682a4e04fee30bfe88a4cd/src/Api/Payment/PaymentApi.php#L35
\Juno::payment->tokenization($creditCardHash);
```

Basicamente, o uso da API se dá por `\Juno::{$API}->{$method}(...$args)`, onde `$API` é qualquer api especificada [nas configurações](https://github.com/jetimob/juno-sdk-php-laravel/blob/master/config/juno.php#L240), por uma chave de `api_impl`.

[Aqui](https://github.com/jetimob/juno-sdk-php-laravel/tree/05c7b3b988deba3aaa682a4e04fee30bfe88a4cd/src/Api) tu consegue encontrar a implementação de todas as APIs disponíveis.

Espero que isso seja suficiente para te dar um norte. Qualquer coisa, se ainda não estiver muito claro, fico à disposição.

Abraço!

**Comment by lpcs007** [comment]
@alanwgt Primeiramente obrigado pelo retorno.

Estou tentando fazer os testes seguindo sua orientação juntamente com as classes e testes, mas estou tendo dificuldade.

```
use Jetimob\Juno\Facades\Juno;
use Jetimob\Juno\Entity\Charge;
use Jetimob\Juno\Entity\Address;
use Jetimob\Juno\Entity\Billing;
```

```
        $billing = Billing::new(
            'Cecília Marcela Brito',
            '09060298993',
            'ceciliamarcelabrito-82@mciimoveis.com.br',
            Address::new(
                'Rua Vieira Portuense',
                '880',
                'São Paulo',
                'SP',
                '04347080'
            )->setNeighborhood('Jardim Oriental')
        );

        $charge = Charge::newWithAmount('Descrição do pagamento', 11.1)->setPaymentTypes([Charge::PAYMENT_TYPE_BOLETO_PIX]);

        $response = Juno::charge->create($charge, $billing);
       
        dd($response);
```

Estou recebendo o seguinte erro:

`Undefined constant Jetimob\Juno\Facades\Juno::charge`

**Comment by lpcs007** [comment]
O erro estava aqui:

`$response = Juno::charge()->create($charge, $billing);`

Obrigado!

**Comment by alanwgt** [comment]
Que bom que conseguiu resolver o problema!

Peço desculpas por ter te passado o exemplo errado anteriormente.

Abraço!
