### ISSUE TITLE
Documentação não está clara! De onde vem o $resourceToken?

### ISSUE THREAD

**Issue by wanderarce** [jetimob/juno-sdk-php-laravel#9]
Os dados foram montados conforme o README.md porém ao realizar requisição do exemplo do prórpio README.md retorna a exception abaixo.

![image](https://user-images.githubusercontent.com/6197730/101985972-70fc2880-3c61-11eb-8d2b-aa9b3b47cd09.png)

The data was assembled according to README.md, however, when requesting the example of README.md itself, the exception below is returned.

! [image] (https://user-images.githubusercontent.com/6197730/101985972-70fc2880-3c61-11eb-8d2b-aa9b3b47cd09.png)

**Comment by wanderarce** [comment]
Correct print for issue 
![image](https://user-images.githubusercontent.com/6197730/101986173-cedd4000-3c62-11eb-95ae-dd134a6e4a99.png)

**Comment by alanwgt** [comment]
Olá!

O $resourceToken é o token fornecido pela Juno (chamado de **X-Resource-Token** na [documentação](https://dev.juno.com.br/api/v2#section/Servidor-de-Autorizacao)) e pode ser encontrado em inúmeras referências, como em:

> Muitos dos recursos também necessitam de um token de recurso, X-Resource-Token que identifica a conta digital que deverá ser utilizada durante a execução de uma operação.
>
> Cada conta digital tem o seu próprio token de recurso. Contas digitais criadas via API incluem o token de recurso na resposta da requisição.
>
> Para obter o token de recurso de uma conta digital já existente ou para redefinir o token de recurso, o cliente precisa acessar o painel do cliente Juno e realizar esta operação na aba Integração, opção Token Privado.

Ou seja, esse token é o identificador da conta digital que está fazendo a requisição à API da Juno.

Por favor, fique a vontade para fazer mais perguntas se não consegui esclarecer as tuas dúvidas. Caso elas tenham sido sanadas, peço para que feche o issue. Obrigado!

**Comment by alanwgt** [comment]
Fechado por inatividade do autor.
